-- MySQL Script generated by MySQL Workbench
-- Sun Sep  5 23:36:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`Mes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`Mes` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `enero` VARCHAR(45) NULL,
    `febrero` VARCHAR(45) NULL,
    `marzo` VARCHAR(45) NULL,
    `abril` VARCHAR(45) NULL,
    `mayo` VARCHAR(45) NULL,
    `junio` VARCHAR(45) NULL,
    `agosto` VARCHAR(45) NULL,
    `septiebre` VARCHAR(45) NULL,
    `octubre` VARCHAR(45) NULL,
    `noviembre` VARCHAR(45) NULL,
    `diciembre` VARCHAR(45) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`ingresos` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `valor` BIGINT(20) NOT NULL,
    `fecha` DATE NOT NULL,
    `created_at` TIMESTAMP(30) NOT NULL,
    `updated_at` TIMESTAMP(30) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`Dia` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `ingreso_dia` BIGINT(20) NOT NULL,
    `fecha` DATE NOT NULL,
    `turno` ENUM('Dia', 'Tarde', 'Noche') NOT NULL,
    `persona` VARCHAR(45) NOT NULL,
    `nombre_ingreso` VARCHAR(45) NOT NULL,
    `Mes_idMes` INT NOT NULL,
    `created_at` TIMESTAMP(30) NOT NULL,
    `updated_at` TIMESTAMP(30) NOT NULL,
    `ingresos_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_Dia_Mes1_idx` (`Mes_idMes` ASC) VISIBLE,
    INDEX `fk_Dia_ingresos1_idx` (`ingresos_id` ASC) VISIBLE,
    CONSTRAINT `fk_Dia_Mes1`
    FOREIGN KEY (`Mes_idMes`)
    REFERENCES `hotel`.`Mes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Dia_ingresos1`
    FOREIGN KEY (`ingresos_id`)
    REFERENCES `hotel`.`ingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`inventario` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `Dia_ingresos_idingresos` INT NOT NULL,
                                                    `Dia_id` INT NOT NULL,
                                                    `Mes_id` INT NOT NULL,
                                                    PRIMARY KEY (`id`),
    INDEX `fk_inventario_Dia1_idx` (`Dia_id` ASC, `Dia_ingresos_idingresos` ASC) VISIBLE,
    INDEX `fk_inventario_Mes1_idx` (`Mes_id` ASC) VISIBLE,
    CONSTRAINT `fk_inventario_Dia1`
    FOREIGN KEY (`Dia_id`)
    REFERENCES `hotel`.`Dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_inventario_Mes1`
    FOREIGN KEY (`Mes_id`)
    REFERENCES `hotel`.`Mes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`habitaciones` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `numero_habitacion` BIGINT(5) NOT NULL,
    `cantidad_personas` BIGINT(5) NOT NULL,
    `precio` BIGINT(20) NOT NULL,
    `Dia_ingresos_idingresos` INT NOT NULL,
    `Estado` ENUM('', 'Caselado', 'No canselado') NOT NULL,
    `inventario_idproducto` INT NOT NULL,
    `ingresos_idingresos` INT NOT NULL,
    `Dia_idDia` INT NOT NULL,
    `updated_at` DATETIME(30) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_habitaciones_inventario1_idx` (`inventario_idproducto` ASC) VISIBLE,
    INDEX `fk_habitaciones_ingresos1_idx` (`ingresos_idingresos` ASC) VISIBLE,
    INDEX `fk_habitaciones_Dia1_idx` (`Dia_idDia` ASC, `Dia_ingresos_idingresos` ASC) VISIBLE,
    CONSTRAINT `fk_habitaciones_inventario1`
    FOREIGN KEY (`inventario_idproducto`)
    REFERENCES `hotel`.`inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_habitaciones_ingresos1`
    FOREIGN KEY (`ingresos_idingresos`)
    REFERENCES `hotel`.`ingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_habitaciones_Dia1`
    FOREIGN KEY (`Dia_idDia`)
    REFERENCES `hotel`.`Dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`clientes` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `nombre` VARCHAR(45) NOT NULL,
    `apellido` VARCHAR(45) NOT NULL,
    `tipo_documento` ENUM('CC', 'Tarjeta', 'Pasaporte') NOT NULL,
    `numero_documento` BIGINT(20) NOT NULL,
    `celular` BIGINT(20) NOT NULL,
    `direccion` VARCHAR(45) NULL,
    `ciudad` VARCHAR(45) NULL,
    `fecha` DATE NOT NULL,
    `hora` VARCHAR(45) NOT NULL,
    `gastos_labanderia` BIGINT(10) NULL,
    `created_at` TIMESTAMP(30) NOT NULL,
    `updated_at` TIMESTAMP(30) NOT NULL,
    `habitaciones_idhabitaciones` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_persona_habitaciones1_idx` (`habitaciones_idhabitaciones` ASC) VISIBLE,
    CONSTRAINT `fk_persona_habitaciones1`
    FOREIGN KEY (`habitaciones_idhabitaciones`)
    REFERENCES `hotel`.`habitaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`gastos` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `Nombre_gasto` VARCHAR(45) NOT NULL,
    `Valor` BIGINT(20) NOT NULL,
    `Fecha` DATE NOT NULL,
    `inventario_idproducto` INT NOT NULL,
    `created_at` TIMESTAMP(30) NOT NULL,
    `updated_at` TIMESTAMP(30) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_gastos_inventario1_idx` (`inventario_idproducto` ASC) VISIBLE,
    CONSTRAINT `fk_gastos_inventario1`
    FOREIGN KEY (`inventario_idproducto`)
    REFERENCES `hotel`.`inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`empleados` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `nombre` VARCHAR(45) NULL,
    `apellido` VARCHAR(45) NULL,
    `cargo` VARCHAR(45) NULL,
    `tipo_documento` ENUM('CC', 'Tarjeta', 'Pasaporte') NULL,
    `documento` BIGINT(20) NULL,
    `turno` ENUM('Dia', 'Tarde', 'Noche') NOT NULL,
    `Salario` BIGINT(20) NOT NULL,
    `celular` BIGINT(20) NULL,
    `direccion` VARCHAR(45) NULL,
    `created_at` TIMESTAMP(30) NULL,
    `updated_at` TIMESTAMP(30) NULL,
    `gastos_idgastos` INT NOT NULL,
    `habitaciones_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_empleados_gastos1_idx` (`gastos_idgastos` ASC) VISIBLE,
    INDEX `fk_empleados_habitaciones1_idx` (`habitaciones_id` ASC) VISIBLE,
    CONSTRAINT `fk_empleados_gastos1`
    FOREIGN KEY (`gastos_idgastos`)
    REFERENCES `hotel`.`gastos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_empleados_habitaciones1`
    FOREIGN KEY (`habitaciones_id`)
    REFERENCES `hotel`.`habitaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`ventas` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `nombre_producto` VARCHAR(45) NOT NULL,
    `precio` BIGINT(20) NOT NULL,
    `fecha` DATE NOT NULL,
    `cantidad` BIGINT(20) NOT NULL,
    `created_at` BIGINT(20) NOT NULL,
    `Dia_id` INT NOT NULL,
    `Dia_ingresos_idingresos` INT NOT NULL,
    PRIMARY KEY (`id`, `Dia_ingresos_idingresos`),
    INDEX `fk_ventas_Dia1_idx` (`Dia_id` ASC, `Dia_ingresos_idingresos` ASC) VISIBLE,
    CONSTRAINT `fk_ventas_Dia1`
    FOREIGN KEY (`Dia_id`)
    REFERENCES `hotel`.`Dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`productos` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `nombre_producto` VARCHAR(45) NOT NULL,
    `cantidad` INT NOT NULL,
    `precio` BIGINT(20) NOT NULL,
    `fecha` DATE NOT NULL,
    `precio_venta` BIGINT(20) NOT NULL,
    `inventario_idproducto` INT NOT NULL,
    `ventas_idventas` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_productos_inventario1_idx` (`inventario_idproducto` ASC) VISIBLE,
    INDEX `fk_productos_ventas1_idx` (`ventas_idventas` ASC) VISIBLE,
    CONSTRAINT `fk_productos_inventario1`
    FOREIGN KEY (`inventario_idproducto`)
    REFERENCES `hotel`.`inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_productos_ventas1`
    FOREIGN KEY (`ventas_idventas`)
    REFERENCES `hotel`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`limpiesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`limpiesa` (
                                                  `id` INT NOT NULL,
                                                  `nuemro_habitacion` BIGINT(5) NOT NULL,
    `fecha` DATE NOT NULL,
    `empleados_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_limpiesa_empleados1_idx` (`empleados_id` ASC) VISIBLE,
    CONSTRAINT `fk_limpiesa_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `hotel`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

USE `hotel` ;

-- -----------------------------------------------------
-- Placeholder table for view `hotel`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `hotel`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`view1`;
USE `hotel`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
